### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sachinkmohan** [zxcv1884/yolov3-onnx-inference#1]
```
File "../yolov3-onnx-inference/yolov3-img.py", line 60, in <module>
    out_boxes, out_scores, out_classes = get_prediction(image_data, image_size)
  File "..//yolov3-onnx-inference/yolov3-img.py", line 34, in get_prediction
    inname[1]: image_size
IndexError: list index out of range
```

I am getting the above error. Could you please check.

**Comment by zxcv1884** [comment]
That's because of your model input shape is different from [yolov3-10.onnx](https://github.com/onnx/models/blob/main/vision/object_detection_segmentation/yolov3/model/yolov3-10.onnx). 
Please make sure the model you used is the same.

**Comment by sachinkmohan** [comment]
Apologies! It is working, i had loaded an invalid onnx file.

Your repository is awesome! :) Appreciate it!!! Thanks for the quick response! 👍🏼
